tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "primary": "#0040e0",
                        "surface-tint": "#124af0",
                        "on-error": "#ffffff",
                        "error": "#ba1a1a",
                        "on-surface-variant": "#434656",
                        "surface-container": "#eceef0",
                        "error-container": "#ffdad6",
                        "on-tertiary": "#ffffff",
                        "tertiary-fixed": "#ffdbcf",
                        "background": "#f7f9fb",
                        "on-error-container": "#93000a",
                        "secondary-fixed": "#d5e3fc",
                        "on-surface": "#191c1e",
                        "on-tertiary-fixed-variant": "#812800",
                        "surface-container-high": "#e6e8ea",
                        "primary-fixed-dim": "#b8c3ff",
                        "primary-container": "#2e5bff",
                        "secondary": "#515f74",
                        "on-secondary-container": "#57657a",
                        "on-secondary-fixed": "#0d1c2e",
                        "inverse-surface": "#2d3133",
                        "surface-dim": "#d8dadc",
                        "on-background": "#191c1e",
                        "inverse-on-surface": "#eff1f3",
                        "on-secondary-fixed-variant": "#3a485b",
                        "on-primary": "#ffffff",
                        "surface": "#f7f9fb",
                        "tertiary-fixed-dim": "#ffb59b",
                        "inverse-primary": "#b8c3ff",
                        "outline": "#747688",
                        "surface-bright": "#f7f9fb",
                        "outline-variant": "#c4c5d9",
                        "surface-container-highest": "#e0e3e5",
                        "on-primary-container": "#efefff",
                        "primary-fixed": "#dde1ff",
                        "secondary-fixed-dim": "#b9c7df",
                        "on-primary-fixed-variant": "#0035be",
                        "on-secondary": "#ffffff",
                        "surface-container-low": "#f2f4f6",
                        "surface-variant": "#e0e3e5",
                        "tertiary-container": "#c24100",
                        "surface-container-lowest": "#ffffff",
                        "tertiary": "#993100",
                        "on-tertiary-container": "#ffece6",
                        "secondary-container": "#d5e3fc",
                        "on-tertiary-fixed": "#380d00",
                        "on-primary-fixed": "#001356"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.125rem",
                        "lg": "0.25rem",
                        "xl": "0.5rem",
                        "full": "0.75rem"
                    },
                    "fontFamily": {
                        "headline": ["Manrope"],
                        "body": ["Inter"],
                        "label": ["Inter"]
                    }
                },
            },
        }
