tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "primary-container": "#2e5bff",
                    "secondary-fixed-dim": "#b9c7df",
                    "on-secondary-fixed-variant": "#3a485b",
                    "on-primary": "#ffffff",
                    "on-secondary-container": "#57657a",
                    "on-background": "#191c1e",
                    "on-surface": "#191c1e",
                    "on-secondary-fixed": "#0d1c2e",
                    "on-primary-container": "#efefff",
                    "inverse-primary": "#b8c3ff",
                    "outline-variant": "#c4c5d9",
                    "tertiary-fixed": "#ffdbcf",
                    "on-surface-variant": "#434656",
                    "primary-fixed-dim": "#b8c3ff",
                    "on-error": "#ffffff",
                    "background": "#f7f9fb",
                    "secondary-fixed": "#d5e3fc",
                    "on-tertiary-container": "#ffece6",
                    "tertiary-fixed-dim": "#ffb59b",
                    "on-error-container": "#93000a",
                    "on-tertiary": "#ffffff",
                    "surface-variant": "#e0e3e5",
                    "secondary": "#515f74",
                    "inverse-surface": "#2d3133",
                    "surface": "#f7f9fb",
                    "surface-container-lowest": "#ffffff",
                    "tertiary": "#993100",
                    "surface-container-highest": "#e0e3e5",
                    "primary-fixed": "#dde1ff",
                    "error": "#ba1a1a",
                    "outline": "#747688",
                    "surface-tint": "#124af0",
                    "surface-bright": "#f7f9fb",
                    "on-primary-fixed-variant": "#0035be",
                    "inverse-on-surface": "#eff1f3",
                    "on-tertiary-fixed": "#380d00",
                    "error-container": "#ffdad6",
                    "surface-container": "#eceef0",
                    "on-tertiary-fixed-variant": "#812800",
                    "surface-container-high": "#e6e8ea",
                    "primary": "#0040e0",
                    "on-primary-fixed": "#001356",
                    "surface-dim": "#d8dadc",
                    "surface-container-low": "#f2f4f6",
                    "tertiary-container": "#c24100",
                    "secondary-container": "#d5e3fc",
                    "on-secondary": "#ffffff"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "fontFamily": {
                    "headline": ["Manrope"],
                    "body": ["Inter"],
                    "label": ["Inter"]
            }
          },
        },
      }
